#!/usr/bin/env ruby

Dir.chdir File.expand_path('..', __dir__) do
  require 'bundler/setup'
end
require 'rubocop/schema'
require 'rubocop/schema/cli'
require 'json'

RuboCop::Schema::CLI.new(Dir.pwd, ENV, ARGV, Dir.home).run
